# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module REXML::Formatters::Transitive; end
module REXML::Formatters::Transitive; end
module REXML::Formatters::Transitive; end
module VisualizeTool::Constants::FORMATS; end
